site_title = "MyArxiv"
limit_days = 7
cache_url = "https://galeselee.github.io/arxiv/cache.json"


[[sources]]
limit = 150
category = "cs.PF"
title = "Performance"

[[sources]]
limit = 150
category = "cs.AR"
title = "Hardware Architecture"


[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"



[[sources]]
limit = 150
category = "cs.OS"
title = "Operating Systems"

[[sources]]
limit = 150
category = "cs.PL"
title = "Programming Languages"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.MM"
title = "Multimedia"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
